### ISSUE TITLE
where <input_file>.json in Example usage of a pretrained model

### ISSUE THREAD

**Issue by ghost** [ndionysus/multitask-cyberthreat-detection#1]
Hi,
please give me <input_file>.json in Example usage of a pretrained model
I do not know set the format of input file <input_file>.json to test model and generate prediction
thanks

**Comment by ndionysus** [comment]
Hello Hashem, 
Apologies for the delay in my reply, unfortunately I've been occupied and couldn't reply sooner.

The addition of that functionality to the code was an afterthought, and it is meant that you substitute or create a new class based on the ExampleClass in the mt_classifier.py file.
The one currently being used (Synapse) is based on an internal tool and hence its json structure won't make much sense outside of it.

Eventually, when I have time I may reorganize this repository in the future to make it easier to run inference tasks.

For now, see if you can use the ExampleClass as a baseline and use your own data structure.
